/**
 * IACMF
 * IaC Compliance Management Framework
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComplianceRuleConfigurationEntity } from './complianceRuleConfigurationEntity';
import { ExecutionEntity } from './executionEntity';
import { IssueFixingReportEntity } from './issueFixingReportEntity';
import { KVEntity } from './kVEntity';


export interface ComplianceIssueEntity { 
    id: number;
    execution?: ExecutionEntity;
    complianceRuleConfiguration?: ComplianceRuleConfigurationEntity;
    fixingReports?: Array<IssueFixingReportEntity>;
    properties?: Array<KVEntity>;
    description?: string;
    type: string;
}

