/**
 * IACMF
 * IaC Compliance Management Framework
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PluginUsageEntity } from './pluginUsageEntity';
import { ComplianceRuleConfigurationEntity } from './complianceRuleConfigurationEntity';
import { ExecutionEntity } from './executionEntity';
import { ProductionSystemEntity } from './productionSystemEntity';
import { TriggerEntity } from './triggerEntity';


export interface ComplianceJobEntity { 
    id: number;
    name: string;
    description?: string;
    triggers?: Array<TriggerEntity>;
    complianceRuleConfigurations?: Array<ComplianceRuleConfigurationEntity>;
    executions?: Array<ExecutionEntity>;
    modelRefinementStrategy?: Array<PluginUsageEntity>;
    checkingPluginUsage?: PluginUsageEntity;
    reportingPluginUsage?: PluginUsageEntity;
    productionSystem?: ProductionSystemEntity;
}

