/**
 * IACMF
 * IaC Compliance Management Framework
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PluginConfigurationEntryDescriptor } from './pluginConfigurationEntryDescriptor';


export interface PluginPojo { 
    identifier?: string;
    description?: string;
    pluginType?: PluginPojo.PluginTypeEnum;
    configurationEntryNames?: Array<PluginConfigurationEntryDescriptor>;
}
export namespace PluginPojo {
    export type PluginTypeEnum = 'MODEL_CREATION' | 'MODEL_REFINEMENT' | 'ISSUE_CHECKING' | 'ISSUE_FIXING' | 'VALIDATION' | 'REPORTING';
    export const PluginTypeEnum = {
        ModelCreation: 'MODEL_CREATION' as PluginTypeEnum,
        ModelRefinement: 'MODEL_REFINEMENT' as PluginTypeEnum,
        IssueChecking: 'ISSUE_CHECKING' as PluginTypeEnum,
        IssueFixing: 'ISSUE_FIXING' as PluginTypeEnum,
        Validation: 'VALIDATION' as PluginTypeEnum,
        Reporting: 'REPORTING' as PluginTypeEnum
    };
}


