/**
 * IACMF
 * IaC Compliance Management Framework
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductionSystemEntity } from './productionSystemEntity';
import { PluginConfigurationEntity } from './pluginConfigurationEntity';
import { IssueFixingConfigurationEntity } from './issueFixingConfigurationEntity';
import { ComplianceJobEntity } from './complianceJobEntity';


export interface PluginUsageEntity { 
    pluginIdentifier: string;
    pluginConfiguration?: Array<PluginConfigurationEntity>;
    id: number;
    complianceJobRefinement?: ComplianceJobEntity;
    refinementPluginIndexInComplianceJob?: number;
    complianceJobChecking?: ComplianceJobEntity;
    issueFixingConfiguration?: IssueFixingConfigurationEntity;
    productionSystem?: ProductionSystemEntity;
}

