/**
 * IACMF
 * IaC Compliance Management Framework
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PluginUsageEntity } from './pluginUsageEntity';
import { ExecutionEntity } from './executionEntity';


export interface PluginUsageInstanceEntity { 
    pluginIdentifier: string;
    id: number;
    pluginUsage?: PluginUsageEntity;
    execution?: ExecutionEntity;
}

